language: objective-c
osx_image: xcode7.3
before_install:
        - brew update
        - brew install xctool || true
        - brew upgrade xctool || true
        - brew install carthage || true
        - brew upgrade carthage || true
        - gem install bundler
        - bundle install
        - export LC_ALL="en_US.UTF-8"
        - pod repo update
        - carthage bootstrap --platform OSX --no-use-binaries
script:
#        - xctool -workspace Amethyst.xcworkspace -scheme Amethyst test
        - xcodebuild -workspace Amethyst.xcworkspace -scheme Amethyst test
